// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1671465092);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7b95a4e3-abc7-4419-a534-ff08bfe811b3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1671465087314");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1671486687314");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1671465069");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1671465065);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"home-button\",\"stop-reload-button\",\"urlbar-container\",\"save-to-pocket-button\",\"privatebrowsing-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"developer-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":5}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("distribution.Parrot.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "102.5.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "590fd5a09e0743b0beb6f3286d54d63b");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20221107191025");
user_pref("extensions.lastAppVersion", "102.5.0");
user_pref("extensions.lastPlatformVersion", "102.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f0a097c5-3853-4ade-945e-9ef32b37256e\",\"formautofill@mozilla.org\":\"a996bb22-4973-40bc-9601-55bbee02ee6c\",\"pictureinpicture@mozilla.org\":\"0f6d9147-b87c-4ef5-8614-32f487891ace\",\"screenshots@mozilla.org\":\"3add1862-633c-45ff-9cf7-2de64431f800\",\"webcompat-reporter@mozilla.org\":\"4f900b80-41f3-4117-9e30-572f38e582d2\",\"webcompat@mozilla.org\":\"4b06c9fe-d017-4535-aa37-ef67c48d9070\",\"uBlock0@raymondhill.net\":\"1508213b-d8c9-44ab-a1e9-91a0acfda7da\",\"addons-search-detection@mozilla.com\":\"f3f32f9d-7b5f-4681-b388-3e42cba779c1\",\"google@search.mozilla.org\":\"11534c43-b32b-44f0-8f07-3a643ae5bdeb\",\"amazondotcom@search.mozilla.org\":\"2760f98a-72a0-4cf7-9610-879f0ec52ef1\",\"wikipedia@search.mozilla.org\":\"49efb869-5fd5-43ff-96fb-e0b2bde51420\",\"bing@search.mozilla.org\":\"44a7f30d-60d5-4f7f-896a-badfc792267e\",\"ddg@search.mozilla.org\":\"257fe26a-dd19-482e-be33-3d68eb6882f1\",\"ebay@search.mozilla.org\":\"f3d66c56-f665-4bb0-b8dd-272a4d4f8d57\",\"firefox-compact-dark@mozilla.org\":\"4ced5064-647e-424e-a94b-e10c3bc66913\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1671465100);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8bd7554b-eb25-4579-9b4f-5e8ac6285e6e");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1671465055);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
